name: globook_client
description: "Globook is a e-book application that helps you to read any book"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # File Picker
  file_picker: ^8.1.2

  cupertino_icons: ^1.0.6

  # gRPC communication
  grpc: ^4.0.1

  # Logging and Debugging Processer
  logger: ^2.5.0

  # Caching Image
  cached_network_image: ^3.4.1

  # Storage
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4

  # State Management
  get: ^4.7.2

  # Icon for iOS/Android Icons
  flutter_launcher_icons: ^0.14.3

  # Environment Variables
  envied: ^1.1.1
  flutter_dotenv: ^5.1.0

  # SVG 이미지 렌더링
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.3

  # Internationalization
  intl: ^0.19.0

  # Markdown 렌더링
  flutter_markdown: ^0.6.18

  # Color Picker
  flutter_colorpicker: ^1.0.3

  # Audio Player
  just_audio: ^0.9.36
  path_provider: ^2.1.2

  # Google Sign In
  google_sign_in: ^6.2.1
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #for setting lint
  flutter_lints: ^3.0.0

  #for generating env file
  build_runner: ^2.4.8
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/svg/
    - assets/icons/png/
    - assets/config/.dev.env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
